In [1]:
import sys
import numpy as np
import pandas as pd

from gcnSurrogate.readers.loadConmechGraphs import loadConmechGraphs, _loadConmechGraph
from gcnSurrogate.readers.loadGhGraphs import loadGhGraphs
from gcnSurrogate.visualization.altTrussViz import plotTruss

In [19]:
# baseName = 'data/2D_Truss_v1.3/MATCHdesign_7_N_1000'
baseName = 'data/2D_Truss_v1.3/conmech/design_7_N_1000'

dataDir = baseName+'/'
print(f'reading files from {dataDir}')
conmechGraphs = loadConmechGraphs(dataDir)
maxes = [max(np.abs(graph.y.numpy().flatten())) for graph in conmechGraphs]
source = pd.DataFrame(maxes, columns=['maxes'])
display(source.describe())

dataFile = baseName+'.csv'
print(f'reading {dataFile}')
ghGraphs = loadGhGraphs(dataFile)
maxes = [max(np.abs(graph.y.numpy().flatten())) for graph in ghGraphs]
source = pd.DataFrame(maxes, columns=['maxes'])
display(source.describe())

reading files from data/2D_Truss_v1.3/conmech/design_7_N_1000/


maxes
count  1000.000000
mean      0.137562
std       1.740254
min       0.004530
25%       0.010635
50%       0.016778
75%       0.032392
max      46.419552

reading data/2D_Truss_v1.3/conmech/design_7_N_1000.csv


maxes
count  1000.000000
mean      0.137562
std       1.740254
min       0.004530
25%       0.010635
50%       0.016778
75%       0.032392
max      46.419552

In [20]:
# is the result discrepancy with old data due to geometry?
# no, all disps are off by a constant factor
ghGraphsOld = loadGhGraphs('data/2D_Truss_v1.3/gh/design_7_N_1000.csv')

In [21]:
ghGraphs[0].pos

tensor([[  0.0000,   0.0000],
        [  6.2457,  -9.5559],
        [  7.1429,   0.0000],
        [ 10.9957, -20.0149],
        [ 14.2857,   0.0000],
        [ 17.8343, -13.1152],
        [ 21.4286,   0.0000],
        [ 25.0000,  -4.8333],
        [ 28.5714,   0.0000],
        [ 32.1656, -13.1152],
        [ 35.7143,   0.0000],
        [ 39.0043, -20.0149],
        [ 42.8571,   0.0000],
        [ 43.7543,  -9.5559],
        [ 50.0000,   0.0000]])

In [22]:
ghGraphsOld[0].pos

tensor([[  0.0000,   0.0000],
        [  6.2457,  -9.5559],
        [  7.1429,   0.0000],
        [ 10.9957, -20.0149],
        [ 14.2857,   0.0000],
        [ 17.8343, -13.1152],
        [ 21.4286,   0.0000],
        [ 25.0000,  -4.8333],
        [ 28.5714,   0.0000],
        [ 32.1656, -13.1152],
        [ 35.7143,   0.0000],
        [ 39.0043, -20.0149],
        [ 42.8571,   0.0000],
        [ 43.7543,  -9.5559],
        [ 50.0000,   0.0000]])

In [23]:
ghGraphs[0].y

tensor([[ 0.0054, -0.0024],
        [ 0.0054, -0.0001],
        [ 0.0060, -0.0007],
        [ 0.0000,  0.0000],
        [ 0.0068, -0.0054],
        [ 0.0055, -0.0068],
        [ 0.0071, -0.0089],
        [ 0.0072, -0.0087],
        [ 0.0074, -0.0089],
        [ 0.0090, -0.0068],
        [ 0.0077, -0.0054],
        [ 0.0145,  0.0000],
        [ 0.0084, -0.0007],
        [ 0.0091, -0.0001],
        [ 0.0091, -0.0024]])

In [32]:
i = 3
ghGraphsOld[i].y/ghGraphs[i].y

tensor([[1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [   nan,    nan],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504,    nan],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504],
        [1.4504, 1.4504]])

In [25]:
conmechGraphs[0].x

tensor([[ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000, -2.5000],
        [ 0.0000,  0.0000,  0.0000],
        [ 1.0000,  1.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)

In [26]:
(conmechGraphs[0].x!=0).double()

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 0.],
        [1., 1., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]], dtype=torch.float64)